package br.com.auditor.main;

import java.util.ArrayList;
import java.util.List;
import java.util.TimeZone;

import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

import br.com.auditor.domain.EStates;
import br.com.auditor.domain.Quee;
import br.com.auditor.domain.Ticket;
import br.com.auditor.extractor.ExcelDataExtractor;
import br.com.auditor.extractor.ExcelDataQueeExtractor;
import br.com.auditor.policies.ETicketAgeGroupPolicies;

public class ReportGenerator {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		
		List<Quee> quees= ExcelDataQueeExtractor.extractQueeListFromCSVFile("WebContent/quee.production.csv");
		List<Ticket> tickets= ExcelDataExtractor.extractTicketListFromCSVData("WebContent/report.csv", quees);
		
		System.out.println("Total de tickets extraidos: "+tickets.size()+"\n");
		
		List<Ticket> ticketdSixtyOrMoreOlder= new ArrayList<Ticket>();
		for (Ticket ticket : tickets) {
			if(ticket.getAge()==ETicketAgeGroupPolicies.SIXTYOROLDER) {
				ticketdSixtyOrMoreOlder.add(ticket);
			}
		}
		
		List<Ticket> ticketdTenDaysOrLess= new ArrayList<Ticket>();
		for (Ticket ticket : tickets) {
			if(ticket.getAge()==ETicketAgeGroupPolicies.LESSTHANOREQUALTENDAYS) {
				ticketdTenDaysOrLess.add(ticket);
			}
		}
		
		List<Ticket> ticketsBetweenElevenOrThirtyDays= new ArrayList<Ticket>();
		for (Ticket ticket : tickets) {
			if(ticket.getAge()==ETicketAgeGroupPolicies.BETWEENELEVENANDTHIRTY) {
				ticketsBetweenElevenOrThirtyDays.add(ticket);
			}
		}
		
		List<Ticket> ticketsBetweenThirtyOrSixtyDays= new ArrayList<Ticket>();
		for (Ticket ticket : tickets) {
			if(ticket.getAge()==ETicketAgeGroupPolicies.BETWEENTHIRTYORSIXTYDAYS) {
				ticketsBetweenThirtyOrSixtyDays.add(ticket);
			}
		}
		
		// Now we need to group by quee
		// We still dont know our quees, so lets identify in primitive way
		
		// We eill need a date formatter
		DateTimeFormatter parser = DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss");
		DateTime jodaTime;
		
		int newTickets= 0;
		int openTickets= 0;
		
		int totalTickets= 0;
		
		for (Quee quee : quees) {
			System.out.println(quee.getName());
			System.out.println("\n");
			
			System.out.println("----- TICKETS COM 10 DIAS OU MENOS: ");
			for(Ticket ticket : ticketdTenDaysOrLess) {
				if(quee.getName().compareTo(ticket.getCurrentState().getQuee().getName())==0){
					jodaTime = new DateTime(ticket.getOpenDate().getTimeInMillis(),DateTimeZone.forTimeZone(TimeZone.getTimeZone("US/Central")));
					System.out.println(ticket.toString());
					System.out.println("****************");
					totalTickets++;
					
					if(EStates.NEW.compareTo(ticket.getCurrentState().getState())==0) {
						newTickets++;
					} else {
						openTickets++;
					}
				}
			}
			System.out.println("TOTAL: "+totalTickets+" \n\n");
			totalTickets= 0;	
			
			System.out.println("----- TICKETS ENTRE 11 E 30 DIAS: ");
			for(Ticket ticket : ticketsBetweenElevenOrThirtyDays) {
				if(quee.getName().compareTo(ticket.getCurrentState().getQuee().getName())==0){
					System.out.println(ticket.toString());
					System.out.println("****************");
					totalTickets++;
					
					if(EStates.NEW.compareTo(ticket.getCurrentState().getState())==0) {
						newTickets++;
					} else {
						openTickets++;
					}
				}
			}
			System.out.println("TOTAL: "+totalTickets+" \n\n");
			totalTickets= 0;
			
			System.out.println("----- TICKETS ENTRE 30 E 60 DIAS: ");
			for(Ticket ticket : ticketsBetweenThirtyOrSixtyDays) {
				if(quee.getName().compareTo(ticket.getCurrentState().getQuee().getName())==0){
					System.out.println(ticket.toString());
					System.out.println("****************");
					totalTickets++;
					
					if(EStates.NEW.compareTo(ticket.getCurrentState().getState())==0) {
						newTickets++;
					} else {
						openTickets++;
					}
				}
			}
			System.out.println("TOTAL: "+totalTickets+" \n\n");
			totalTickets= 0;
			
			System.out.println("----- TICKETS COM 60 DIAS OU MAIS: ");
			for(Ticket ticket : ticketdSixtyOrMoreOlder) {
				if(quee.getName().compareTo(ticket.getCurrentState().getQuee().getName())==0){
					System.out.println(ticket.toString());
					System.out.println("****************");
					totalTickets++;
					
					if(EStates.NEW.compareTo(ticket.getCurrentState().getState())==0) {
						newTickets++;
					} else {
						openTickets++;
					}
				}
			}
			
			System.out.println("New: "+newTickets);
			System.out.println("Open: "+openTickets);
			System.out.println("TOTAL: "+totalTickets+" \n\n\n");
			totalTickets= 0;
			newTickets= 0;
			openTickets=0;
		}
		
		System.out.println("-----------------------------------------------------------");
		System.out.println("Generated by OTRS Auditor\n\n\n\n\n\n\n");
	}

}
